services:
  backend:
    build:
      context: ./backend
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

  mongo:
    image: mongo:latest
